version: '3'

services:
  webapp:
    image: sarboleda22/talking_cub_web:latest
    ports:
      - 8000:80
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:11.1
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=talking_cub
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped

  watchtower:
    image: v2tec/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

volumes:
  pgdata: {}
